### ISSUE TITLE
License status

### ISSUE THREAD

**Issue by rektdeckard** [mdbel/svg2png#8]
Hey @mdbel, I notice there is no license associated with this library! I'd like to use it in a project of my own, [Phosphor Icons](https://github.com/phosphor-icons/phosphor-web), which is MIT-licensed. Are you comfortable with that, and if so would you be willing to adopt a permissive license (like MIT) for svg2png?

**Comment by mdbel** [comment]
Hey @rektdeckard  yes, MIT is fine. just added this license!
